name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set DATE var
        run: echo "DATE=$(date '+%Y-%m-%d_%H.%M.%S')" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/h265ize:latest
            "${{ secrets.DOCKER_USERNAME }}/h265ize:${{ env.DATE }}"
